### ISSUE TITLE
Why does the response appear in HTML format instead of json format when I run it?

### ISSUE THREAD

**Issue by Bkinsjuwo** [Nipun1212/Claude_api#5]
Why does the response appear in HTML format instead of json format when I run it?

**Comment by Nipun1212** [comment]
which function are you calling to get the response. and can you send the picture of the issue.
Thanks

**Comment by rosa-lie** [comment]
i have encountered a similar error.
`
def get_organization_id(self):
    url = "https://claude.ai/api/organizations"

    headers = {
        'User-Agent':
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/115.0',
        'Accept-Language': 'en-US,en;q=0.5',
        'Referer': 'https://claude.ai/chats',
        'Content-Type': 'application/json',
        'Sec-Fetch-Dest': 'empty',
        'Sec-Fetch-Mode': 'cors',
        'Sec-Fetch-Site': 'same-origin',
        'Connection': 'keep-alive',
        'Cookie': f'{self.cookie}'
    }

    response = requests.get(url, headers=headers, impersonate="chrome110")
    res = json.loads(response.text)
    uuid = res[0]['uuid']

    return uuid
`


Traceback (most recent call last):
  File "xxxxxx\Claude-API-main\usecases\console_chat.py", line 32, in <module>
    main()
  File "xxxxxxxxxxxxxx\Claude-API-main\usecases\console_chat.py", line 12, in main
    claude = Client(cookie)
  File "xxxxxxxx\Claude-API-main\claude-api\claude_api.py", line 13, in __init__
    self.organization_id = self.get_organization_id()
  File "xxxxxxx\Claude-API-main\claude-api\claude_api.py", line 33, in get_organization_id
    res = json.loads(response.text)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 9 (char 9)

**Comment by rosa-lie** [comment]
https://stackoverflow.com/questions/57685622/json-decoder-jsondecodeerror-expecting-value-line-1-column-1-char-0-python

might help
